name: Daily Commit Bot

on:
  schedule:
    # Runs every day at 05:30 UTC
    - cron: "30 5 * * *"
  workflow_dispatch:

jobs:
  commit-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Daily Commit with 25ds3000118@ds.study.iitm.ac.in
        run: |
          date >> daily-log.txt
          git config --local user.email "25ds3000118@ds.study.iitm.ac.in"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Daily update"
          git push
